### ISSUE TITLE
Add command to detect breaking changes in .parquet schemas using SchemaDDL

### ISSUE THREAD

**Issue by marcin-j** [snowplow/igluctl#140]
Hello!

I was wondering if it would be possible to add schema validation mechanism to detect breaking changes, regarding .parquet files. It would be great to have some static command like`igluctl databricks validate` (or similar). As I understand `snowplow-rdb-loader` is using [this code](https://github.com/snowplow/schema-ddl/blob/master/modules/core/src/main/scala/com.snowplowanalytics/iglu.schemaddl/parquet/Migrations.scala) to detect breaking changes and prepare `recovery` columns.

Would it be possible to add this kind of command to igluctl as well?

**Comment by voropaevp** [comment]
Related work in done in https://github.com/snowplow/igluctl/issues/148
