### ISSUE TITLE
Add `verify-parquet` command

### ISSUE THREAD

**Issue by pondzix** [snowplow/igluctl#148]
Add `verify-parquet` command which would allow to detect breaking changes within Iglu schema family (schemas with the same vendor, name and version model). 

Input: path to directory with JSON schemas.
Output: list of potential breaking changes introduced by broken schema.
Usage: `igluctl static verify-parquet $input_schemas_dir`

To detect breaking changes we can use schema-ddl [code](https://github.com/snowplow/schema-ddl/blob/df9978606feb67b4e737e150f445ca4328e3c811/modules/core/src/main/scala/com.snowplowanalytics/iglu.schemaddl/parquet/Migrations.scala#L182). It is already used by the RDB [transformer](https://github.com/snowplow/snowplow-rdb-loader/blob/master/modules/common/src/main/scala/com/snowplowanalytics/snowplow/rdbloader/common/transformation/parquet/NonAtomicFieldsProvider.scala#L67) to create recovered columns.

**Comment by marcin-j** [comment]
hm, looks like those issues are strictly related https://github.com/snowplow/igluctl/issues/140

**Comment by voropaevp** [comment]
@marcin-j you are correct it is the same issue. I am going to close the original one.
